### ISSUE TITLE
Dont work in Mainnet

### ISSUE THREAD

**Issue by dayman8888** [web3chick/Hashlips-Minting-Dapp-With-Web3-Modal#1]
metamask is not called.
if I set the default ABI, then the metamask is called.

**Comment by web3chick** [comment]
> metamask is not called. if I set the default ABI, then the metamask is called.

You need to replace the Config files information with the mainnet information. Also in the Src> App.js, update the smart contract call function (line after blockchain.smartContract.methods) in line 311 (if you are not using the default contract).
